### ISSUE TITLE
Duplicating data

### ISSUE THREAD

**Issue by serchavalos** [NV/chrome-devtools-autosave#62]
There are some situations where the new version of the file is appended at the beginning of it, duplicating the content of it.

For example, after it saves the changes, the output of the file is:

/main.css
/* New version*/
body {background-color: black}
/* Old version*/
body {background-color: white}

Most likely this was occurred because I had the same CSS file opened in my editor (Sublime2 to be precise) causing these conflicts. 

However, I think this case of having the editor opened and editing in the browser it's quite common (especially when adding new CSS class, a task current can't be done in Chrome Dev tool)

**Comment by NV** [comment]
I haven't experienced this problem for a very long time. Closing.
