### ISSUE TITLE
Can't add new projects after update Chrome 45.0.2454.85

### ISSUE THREAD

**Issue by pen18** [NV/chrome-devtools-autosave#97]
The drag function stopped working after update Chrome 45.0.2454.85 ?
Please help me or tell me alternative.

![2015-09-13 13 55 00](https://cloud.githubusercontent.com/assets/14256700/9835308/dd294d28-5a1f-11e5-987e-f8e52e086bb2.png)

**Comment by AFlorencia** [comment]
The same happens to me. Trying Tincr

**Comment by pen18** [comment]
I used Tincr before Devtools Autosave. But Tincr didn't become working.
I'm trying [workspaces](https://developer.chrome.com/devtools/docs/workspaces) now.

**Comment by AFlorencia** [comment]
Yes, I noticed the same. Learning to use workspaces now. 
Good luck!

**Comment by kmsdevnet** [comment]
I had the same issue. What I did is modify the `options.js` file to "avoid" the error. I am happy to say that it's working as it should do it.

So, step one: download the project from github.

Then modify the `options.js` file, go to the line 528 (`Object.defineProperty(SVGGElement.prototype, 'x'.....`) and prepend this:
```javascript
if( this.dataset === undefined ) this.dataset = {};
```
**to the set() method**.

**Do the same** with the next method (`Object.defineProperty(SVGGElement.prototype, 'y'....`).

To finish follow the instructions at http://superuser.com/a/247654/327682.

I had just to declare the dataset object, that (I don't know why) is undefined.

**Comment by NV** [comment]
Fixed in 1.2.4. The extension should update automatically.

@kmsdevnet thank you for explaining what was broken.

**Comment by kmsdevnet** [comment]
I am glad to help. This is a great utility after all :smile:
