### ISSUE TITLE
project status?

### ISSUE THREAD

**Issue by corysimmons** [NV/chrome-devtools-autosave#98]
Is this still under development or do you think workspaces fills this roll now?

I think workspaces is completely useless and there's a huge void to fill there.

**Comment by NV** [comment]
There is no development happening. However, Autosave still works well with the latest stable Chrome.

Why do you think workspaces are useless?

**Comment by corysimmons** [comment]
- doesn't save dom changes
- have to have selectors already existing in .html/.css
- preprocessing is borked (you can change pre-existing scss but if you add a new declaration to a ruleset it applies your changes to the css -- not the scss file)

It just seems half finished.

**Comment by NV** [comment]
> doesn't save dom changes

This one is hard to implement. You probably wouldn't want to save DOM changes made by JS—only by the devtools. There's currently no easy way to distinguish the two.

You may have a better luck asking for this feature on [Chromium bug tracker](https://developer.chrome.com/devtools#get-involved).

> have to have selectors already existing in .html/.css

You can add rules to a specific CSS file:
![add-css-rule](https://cloud.githubusercontent.com/assets/55838/12945858/6a06a782-d044-11e5-9c5d-d05a13c97c03.png)

> preprocessing is borked (you can change pre-existing scss but if you add a new declaration to a ruleset it applies your changes to the css -- not the scss file)

This one is hard to implement, too.

There is something happening with sass/scss in Chrome DevTools: https://code.google.com/p/chromium/issues/detail?id=527993
I don't understand what exactly as they don't talk about the user impact.

---

All your complaints are completely valid, though.

**Comment by corysimmons** [comment]
Awesome, thanks for the help.

It's still unusable and probably will be for the foreseeable future. It's too bad. Live editing could be amazing..

**Comment by corysimmons** [comment]
> You can add rules to a specific CSS file

Unfortunately that doesn't work with preprocessors, just .css -- making it useless.

Sorry I'm cranky. Hate spending hours learning tools just to discover they're complete junk.

Are any of these things possible with your project? Or possible for a third party project at all?

**Comment by NV** [comment]
> Are any of these things possible with your project?

No at this stage, no.

> Or possible for a third party project at all?

None that I know of, I'm afraid.

**Comment by corysimmons** [comment]
Okay, well, thank you.
